"""
Claude AI Trade Advisor
========================
Uses the Claude API to evaluate high-confidence signals before execution.
Claude acts as a senior trader reviewing every Tier 2+ setup.

How it works:
  1. Bot generates a signal via technical indicators (momentum, breakout, etc.)
  2. Confluence engine grades it Tier 1-4
  3. For Tier 2+, this module packages all context and asks Claude:
       "Given everything you know about this setup — should I take this trade?"
  4. Claude returns YES/NO + reasoning + confidence adjustment
  5. A NO from Claude vetoes the trade entirely
  6. A YES unlocks execution with any confidence boost Claude suggests

Why this matters:
  Rules-based systems miss context. Claude can see:
    - Whether the R:R is actually worth the risk given recent performance
    - If the timing makes sense (e.g., don't trade into weekend low liquidity
      if the week has been choppy)
    - If the setup looks textbook but the broader context is wrong
    - Pattern recognition across ALL the data points simultaneously

Cost management:
  Claude is only called for Tier 2+ signals that already passed scoring.
  Typical usage: 5-15 API calls per day = ~$0.05-0.20/day at current rates.
  Prompt caching is used for the system prompt (reduces cost ~90%).
"""
from __future__ import annotations

import asyncio
import logging
import time
from typing import TYPE_CHECKING

log = logging.getLogger("apex.claude")

try:
    import anthropic
    ANTHROPIC_OK = True
except ImportError:
    ANTHROPIC_OK = False
    log.warning("anthropic SDK not installed — run: pip install anthropic")

if TYPE_CHECKING:
    from signals.confluence import ConfluenceResult
    from strategies.base import Signal


# System prompt is cached — only sent once, amortized across all calls
_SYSTEM_PROMPT = """You are a professional quantitative trader with 15 years of experience in crypto derivatives markets. You specialize in momentum, breakout, and carry strategies on perpetual futures.

Your job is to review trading signals generated by an automated system and make final YES/NO execution decisions. You are the last line of defense before real capital is deployed.

Your evaluation framework:
1. Risk/Reward — Is the R:R ratio genuinely attractive given the setup quality?
2. Confidence calibration — Does the stated confidence reflect actual setup quality?
3. Timing — Is this the right moment, or are there red flags (low liquidity hours, choppy recent action)?
4. Recent performance — Is the bot on a hot streak (can run) or struggling (tighten criteria)?
5. Confluence quality — Do the agreeing strategies actually make sense together, or is this spurious?

You are NOT here to approve every trade. A meaningful veto rate (20-30% of Tier 2+ signals) is healthy and expected. Do not rubber-stamp signals.

Respond ONLY in this exact format — no extra text:
DECISION: YES
CONFIDENCE_ADJUSTMENT: +0.05
REASONING: Strong momentum+breakout confluence with tight stop, good R:R, prime hours."""

_CALL_CACHE: dict[str, tuple[bool, str, float]] = {}  # Simple dedup (same signal key)


class ClaudeAdvisor:
    """
    Wraps the Claude API for trade decision-making.
    Thread-safe; uses asyncio executor for the blocking SDK calls.
    """

    def __init__(self, api_key: str, model: str = "claude-opus-4-6"):
        if not ANTHROPIC_OK:
            raise ImportError("pip install anthropic")
        self._client = anthropic.Anthropic(api_key=api_key)
        self._model = model
        self._call_count = 0
        self._veto_count = 0
        self._last_call_ts = 0.0
        # Rate limit: max 1 call per 10 seconds (avoids hammering API during signal bursts)
        self._min_call_interval = 10.0

    async def evaluate(
        self,
        signal: "Signal",
        confluence: "ConfluenceResult",
        recent_stats: dict,
    ) -> tuple[bool, str, float]:
        """
        Ask Claude whether to execute this trade.

        Args:
            signal:        The trading signal to evaluate
            confluence:    Confluence analysis result
            recent_stats:  Dict from RiskManager.get_stats()

        Returns:
            (should_execute, reasoning, confidence_adjustment)
            confidence_adjustment: float in [-0.20, +0.10]
        """
        # Rate limiting
        wait = self._min_call_interval - (time.time() - self._last_call_ts)
        if wait > 0:
            await asyncio.sleep(wait)

        # Dedup: same signal within 60s gets cached answer
        cache_key = f"{signal.pair}:{signal.direction.value}:{signal.entry_price:.0f}"
        if cache_key in _CALL_CACHE:
            return _CALL_CACHE[cache_key]

        import datetime
        utc_hour = datetime.datetime.utcnow().hour
        day_name = datetime.datetime.utcnow().strftime("%A")

        user_message = f"""TRADING SIGNAL FOR REVIEW:

Instrument: {signal.pair} — {signal.direction.value.upper()}
Entry Price:  ${signal.entry_price:,.4f}
Stop Price:   ${signal.stop_price:,.4f}  (risk: {abs(signal.entry_price - signal.stop_price) / signal.entry_price * 100:.2f}%)
Target Price: ${signal.target_price:,.4f}  (reward: {abs(signal.target_price - signal.entry_price) / signal.entry_price * 100:.2f}%)
Risk/Reward:  {signal.risk_reward:.2f}:1
Strategy:     {signal.strategy}
Confidence:   {signal.confidence:.0%}

CONFLUENCE ANALYSIS:
Tier:       {confluence.tier} / 4  ({', '.join(confluence.agreeing_strategies)})
OB Imbalance: {confluence.orderbook_bias:+.2f}  (-1=sell pressure, +1=buy pressure)
Notes:      {'; '.join(confluence.notes) if confluence.notes else 'none'}

RECENT BOT PERFORMANCE:
Balance:     ${recent_stats.get('balance', 0):,.2f}
Daily P&L:   {recent_stats.get('daily_pnl_pct', 0):+.1f}%
Win Rate:    {recent_stats.get('win_rate', 0):.0f}%
Trades Today: {recent_stats.get('trades_today', 0)}
Open Positions: {recent_stats.get('open_positions', 0)}
Drawdown:    {recent_stats.get('drawdown_pct', 0):.1f}%

TIMING:
UTC Hour:  {utc_hour}:00  ({day_name})
Prime Hours (13-17 UTC): {'YES' if 13 <= utc_hour < 18 else 'NO'}

Should I execute this trade?"""

        loop = asyncio.get_event_loop()
        try:
            response = await loop.run_in_executor(
                None,
                lambda: self._client.messages.create(
                    model=self._model,
                    max_tokens=150,
                    system=[
                        {
                            "type": "text",
                            "text": _SYSTEM_PROMPT,
                            "cache_control": {"type": "ephemeral"},  # Cache system prompt
                        }
                    ],
                    messages=[{"role": "user", "content": user_message}],
                ),
            )
            self._last_call_ts = time.time()
            self._call_count += 1

            result = self._parse_response(response.content[0].text)
            _CALL_CACHE[cache_key] = result

            decision, reasoning, adj = result
            if not decision:
                self._veto_count += 1

            log.info(
                "CLAUDE %s: %s %s | adj=%+.2f | '%s' [calls=%d vetoes=%d]",
                "APPROVED" if decision else "VETOED",
                signal.pair, signal.direction.value,
                adj, reasoning, self._call_count, self._veto_count,
            )
            return result

        except Exception as e:
            log.warning("Claude API call failed: %s — allowing trade (fail-open)", e)
            return True, f"API error: {e}", 0.0

    def get_stats(self) -> dict:
        veto_rate = (self._veto_count / self._call_count * 100) if self._call_count else 0
        return {
            "total_calls": self._call_count,
            "vetoes": self._veto_count,
            "veto_rate_pct": round(veto_rate, 1),
        }

    @staticmethod
    def _parse_response(text: str) -> tuple[bool, str, float]:
        """Parse Claude's structured response."""
        lines = [l.strip() for l in text.strip().split("\n") if l.strip()]
        decision = True
        adj = 0.0
        reasoning = "No reasoning provided"

        for line in lines:
            if line.startswith("DECISION:"):
                decision = "YES" in line.upper()
            elif line.startswith("CONFIDENCE_ADJUSTMENT:"):
                try:
                    val = line.split(":", 1)[1].strip()
                    adj = float(val)
                    adj = max(-0.20, min(0.10, adj))   # Clamp to safe range
                except (ValueError, IndexError):
                    pass
            elif line.startswith("REASONING:"):
                reasoning = line.split(":", 1)[1].strip()

        return decision, reasoning, adj
